# Generated by Django 3.2.7 on 2021-11-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpay', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(max_length=110)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
