# Generated by Django 3.2.7 on 2021-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpay', '0007_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='10000'),
        ),
    ]
